/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void modeStandard_clicked1(GOption source, GEvent event) { //_CODE_:modeStandard:350131:
  mode("std");
} //_CODE_:modeStandard:350131:

public void modeCircle_clicked1(GOption source, GEvent event) { //_CODE_:modeCircle:838670:
  mode("circle");
} //_CODE_:modeCircle:838670:

public void modeEight_clicked1(GOption source, GEvent event) { //_CODE_:modeEight:569870:
  mode("eight");
} //_CODE_:modeEight:569870:

public void buttonTargetOrg_click1(GButton source, GEvent event) { //_CODE_:buttonTargetOrg:450617:
  targetOrg();
} //_CODE_:buttonTargetOrg:450617:

public void switchCircleDir_click1(GButton source, GEvent event) { //_CODE_:switchCircleDir:859161:
  switchCircleDir();
} //_CODE_:switchCircleDir:859161:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("2d balancer");
  view1 = new GView(this, 190, 10, 600, 450, JAVA2D);
  togGroup1 = new GToggleGroup();
  modeStandard = new GOption(this, 10, 60, 80, 20);
  modeStandard.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  modeStandard.setText("Standard");
  modeStandard.setOpaque(false);
  modeStandard.addEventHandler(this, "modeStandard_clicked1");
  modeCircle = new GOption(this, 10, 80, 80, 20);
  modeCircle.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  modeCircle.setText("Circle");
  modeCircle.setOpaque(false);
  modeCircle.addEventHandler(this, "modeCircle_clicked1");
  modeEight = new GOption(this, 10, 100, 80, 20);
  modeEight.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  modeEight.setText("Eight");
  modeEight.setOpaque(false);
  modeEight.addEventHandler(this, "modeEight_clicked1");
  togGroup1.addControl(modeStandard);
  modeStandard.setSelected(true);
  togGroup1.addControl(modeCircle);
  togGroup1.addControl(modeEight);
  xyLabel = new GLabel(this, 80, 10, 60, 20);
  xyLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  xyLabel.setText("-100 / -80");
  xyLabel.setOpaque(false);
  label1 = new GLabel(this, 10, 10, 60, 20);
  label1.setText("x/y");
  label1.setOpaque(false);
  label2 = new GLabel(this, 10, 30, 60, 20);
  label2.setText("target x/y");
  label2.setOpaque(false);
  xyTarget = new GLabel(this, 80, 30, 60, 20);
  xyTarget.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  xyTarget.setText("0 / 0");
  xyTarget.setOpaque(false);
  buttonTargetOrg = new GButton(this, 150, 30, 30, 20);
  buttonTargetOrg.setText("0/0");
  buttonTargetOrg.addEventHandler(this, "buttonTargetOrg_click1");
  switchCircleDir = new GButton(this, 100, 80, 80, 20);
  switchCircleDir.setText("switch dir");
  switchCircleDir.addEventHandler(this, "switchCircleDir_click1");
}

// Variable declarations 
// autogenerated do not edit
GView view1; 
GToggleGroup togGroup1; 
GOption modeStandard; 
GOption modeCircle; 
GOption modeEight; 
GLabel xyLabel; 
GLabel label1; 
GLabel label2; 
GLabel xyTarget; 
GButton buttonTargetOrg; 
GButton switchCircleDir; 
